from __future__ import annotations

import json
import os
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


PROJECT_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT = PROJECT_ROOT.parent
ENV_FILES = (WORKSPACE_ROOT / ".env", PROJECT_ROOT / ".env")
PLACEHOLDER_VALUES = {
    "PUT_WORKLOGIX_API_URL_HERE",
    "PUT_WORKLOGIX_EMAIL_HERE",
    "PUT_WORKLOGIX_PASSWORD_HERE",
    "PUT_WORKLOGIX_JWT_TOKEN_HERE",
}


class WorklogixConfigError(RuntimeError):
    pass


class WorklogixAuthError(RuntimeError):
    pass


def load_env_file(path: Path) -> None:
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def load_worklogix_env() -> None:
    for env_file in ENV_FILES:
        load_env_file(env_file)


def get_required_env(*names: str) -> str:
    load_worklogix_env()
    for name in names:
        value = os.environ.get(name, "").strip()
        if value and value not in PLACEHOLDER_VALUES:
            return value
    joined = " or ".join(names)
    raise WorklogixConfigError(f"Set {joined} in .env with a real value instead of the placeholder.")


def get_optional_token() -> str:
    load_worklogix_env()
    token = os.environ.get("WORKLOGIX_JWT_TOKEN", "").strip()
    return "" if token in PLACEHOLDER_VALUES else token


def worklogix_base_url() -> str:
    return get_required_env("WORKLOGIX_API_BASE_URL", "WORKLOGIX_BASE_URL").rstrip("/")


def login() -> str:
    # If a valid JWT is already present in .env, reuse it and skip login.
    token = get_optional_token()
    if token:
        return token

    # Login happens here using only .env values. No credentials are hardcoded.
    base_url = worklogix_base_url()
    email = get_required_env("WORKLOGIX_EMAIL")
    password = get_required_env("WORKLOGIX_PASSWORD")
    payload = json.dumps({"email": email, "password": password}).encode("utf-8")
    http_request = Request(
        f"{base_url}/api/v1/login",
        data=payload,
        headers={"Accept": "application/json", "Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urlopen(http_request, timeout=30) as response:
            body = response.read().decode("utf-8")
            data = json.loads(body) if body else {}
    except HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        if exc.code == 401:
            raise WorklogixAuthError("Worklogix login failed: invalid email or password.") from exc
        if exc.code == 403:
            raise WorklogixAuthError("Worklogix login failed: access forbidden for this account.") from exc
        if exc.code == 404:
            raise WorklogixAuthError("Worklogix login endpoint not found. Check WORKLOGIX_API_BASE_URL.") from exc
        raise WorklogixAuthError(f"Worklogix login failed with HTTP {exc.code}: {body}") from exc
    except URLError as exc:
        raise WorklogixAuthError(f"Unable to reach Worklogix login API: {exc.reason}") from exc
    except TimeoutError as exc:
        raise WorklogixAuthError("Worklogix login timed out after 30 seconds.") from exc
    except json.JSONDecodeError as exc:
        raise WorklogixAuthError("Worklogix login returned invalid JSON.") from exc

    if data.get("is_verified") is False:
        raise WorklogixAuthError("Worklogix login succeeded but the user is not verified.")
    if isinstance(data.get("data"), dict) and data["data"].get("is_verified") is False:
        raise WorklogixAuthError("Worklogix login succeeded but the user is not verified.")

    # The JWT token is generated by the login API and extracted here.
    jwt_token = data.get("jwt_token") or data.get("token") or data.get("access_token")
    if not jwt_token and isinstance(data.get("data"), dict):
        jwt_token = data["data"].get("jwt_token") or data["data"].get("token")
    if not jwt_token:
        raise WorklogixAuthError("Worklogix login succeeded but jwt_token was not found in the response.")
    return jwt_token
